# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/fommil/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags:
  xmonad-contrib:
    use_xft: true
  xmobar:
    with_xft: true
extra-package-dbs: []
packages: []
extra-deps:
  - xmonad-0.13
  - xmonad-contrib-0.13
  - xmobar-0.24
resolver: lts-8.21
